### ISSUE TITLE
Selecting paths for settings are full or relative?

### ISSUE THREAD

**Issue by emollusion** [wilhelmer/mkdocs-multirepo#3]
Hi!

After trying to figure out how to configure the multi repo in config.yml, I get hold up on these settings:
`mkdocs_dir`
`mkdocs_config`
`index_html`

*mkdocs_dir* seems to work with relative path, relative to the repo, as the documentations suggests.

Pointing out the relative path within the repo to mkdocs.yml does not seem to work, it does not find that file.
Providing a full path does work though.

Not sure if this is intended behaviour?

Either way, a relative path to the repo would make more sense and work better I believe.

Thanks for the good work!

**Comment by wilhelmer** [comment]
@Jofi contributed these settings, maybe he can assist here.

Usually, the `mkdocs.yml` is in the root dir of the repo, so you shouldn't need to point `mkdocs_config` to a path, only to a file, e.g., `custom.yml`. Or, if the file is named `mkdocs.yml`, you don't have to use this setting at all.

If your `mkdocs.yml` really is in a different directory than the other MkDocs files, which is not recommended, you have to set `docs_dir` within the `mkdocs.yml` file so that MkDocs can find your Markdown files, e.g.,

```yml
site_name: Sample mkdocs template
docs_dir: ../docs
nav:
  - Home: index.md
  - Install: install.md
  - Full Example: example.md
```
